version: '3.9'
services:
  tour-de-france-mvc:
    image: proasacio/final-project-mvc:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - tour-network

  tour-de-france-db:
    image: proasacio/final-project-db:latest
    ports:
      - "5432:5432"
    restart: always
    networks:
      - tour-network
      
networks:
  tour-network:
