version: '3.9'
services:
  final-project-mvc:
    image: proasacio/final-project-mvc:latest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - final-project-network
    depends_on:
      - final-project-db

  final-project-db:
    image: proasacio/final-project-db:latest
    ports:
      - "5432:5432"
    restart: always
    networks:
      - final-project-network
      
networks:
  final-project-network:
