
trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'proasacio-docker-hub'
        repository: 'proasacio/final-project-mvc'
        command: 'buildAndPush'
        Dockerfile: 'docker/Dockerfile'
        buildContext: '.'
        tags: 'latest'

- stage: Deploy
  displayName: Deploy to server
  dependsOn: Build
  jobs:
  - job: 
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DownloadSecureFile@1
      name: sshKey
      inputs:
        secureFile: 'default-ec2.pem'
    - script: |
        echo "Setting permissions for SSH key"
        chmod 400 $(SSH_PRIVATE_KEY)  # Ensure the private key has the correct permissions
        ssh -o StrictHostKeyChecking=no -i $(SSH_PRIVATE_KEY) ec2-user@ec2-54-236-25-144.compute-1.amazonaws.com
      displayName: 'SSH and Run Ansible Playbook'
      env:
        SSH_PRIVATE_KEY: $(sshKey)