
trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'proasacio-docker-hub'
        repository: 'proasacio/final-project-mvc'
        command: 'buildAndPush'
        Dockerfile: 'docker/Dockerfile'
        buildContext: '.'